include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - android/**
    - ios/**
    - lib/**/*.g.dart
    - lib/*.g.dart
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - statrack-web/**

  errors:
    missing_return: error
    dead_code: error
    invalid_annotation_target: error
    invalid_assignment: error
    non_bool_condition: error
    throw_in_finally: error

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Dart Core
    - always_declare_return_types
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_print
    - avoid_catches_without_on_clauses
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_catches
    - empty_statements
    - hash_and_equals
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks

    # Flutter
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_positional_boolean_parameters
    - avoid_types_on_closure_parameters
    - camel_case_types
    - lines_longer_than_80_chars
    - flutter_style_todos
    - prefer_const_constructors
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - "**/*.g.dart"
    - "**/*.freezed.dart"