name: football_stat_track
description: Local-first mobile app for tracking sports statistics

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  uuid: ^4.6.0
  intl: ^0.20.3
  vibration: ^3.0.0

dependency_overrides:
  intl: ^0.19.0
  url_launcher: ^6.1.11
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  analyzer: ^5.13.0

flutter:
  uses-material-design: true